name: sempy
channels:
- conda-forge
dependencies:
- fsspec=2023.3.0
- geopandas=0.12.2
- graphviz=2.50.0
- ipykernel=6.21.3
- ipython=8.9.0
- matplotlib=3.6.3
- numpy=1.23.5
- pandas=1.5.3
- pandoc=2.19.2
- pip=23.0.1
- pyarrow=11.0.0
- pyspark=3.3.1
- python=3.10
- python-graphviz=0.20.1
- seaborn=0.12.2
- sqlalchemy=2.0.5.post1
- scikit-learn=1.2.2
- flake8
- pytest
- pytest-cov
- pytest-mock
- geodatasets
- fluent-logger==0.10.0
- coverage
- requests-mock
- pip:
  - pythonnet==3.0.1
  - azure-identity==1.7.1
  - azure-keyvault-secrets
  - azure-storage-file-datalake==12.3.1
  - azure-storage-blob>=12.9.0
