name: sempy
channels:
- conda-forge
dependencies:
- fsspec=2023.3.0
- geopandas=0.12.2
- graphviz=2.50.0
- ipykernel=6.21.3
- ipython=8.9.0
- matplotlib=3.6.3
- numpy=1.23.5
- pandas=1.5.3
- pandoc=2.19.2
- pip=23.0.1
- pyarrow=11.0.0
- pyspark=3.3.1
- python=3.10
- python-graphviz=0.20.1
- seaborn=0.12.2
- sqlalchemy=2.0.5.post1
- scikit-learn=1.2.2
- pip:
  - pythonnet==3.0.1
