name: Semantic Link Functions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        package: ["geopandas", "holidays", "meteostat", "phonenumbers", "validators"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ steps.get-date.outputs.today }}-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: sempy
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          channel-priority: strict
          use-only-tar-bz2: true # # IMPORTANT: This needs to be set for caching to work properly!

      - name: Install packages
        run: |
          cd ${{ matrix.package }}
          pip install -e .

      - name: Lint with flake8
        run: |
          cd ${{ matrix.package }}
          flake8 . --count --show-source --statistics

      - name: Test with pytest
        run: |
          cd ${{ matrix.package }}
          pytest -s tests/